# Generated by Django 6.0.2 on 2026-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_mate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplanitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
