# Generated by Django 6.0.2 on 2026-04-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_mate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplanitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_study_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
