# Generated by Django 5.2.11 on 2026-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_mate_app', '0002_studyplanitem_status_alter_user_daily_study_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_study_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_avatar.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='xp_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studyplanitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
