# Generated by Django 5.2.11 on 2026-04-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_mate_app', '0002_studyplanitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplanitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_study_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
