# Generated by Django 5.2.11 on 2026-04-14 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_mate_app', '0006_studysession_study_plan_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='study_plan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_sessions', to='study_mate_app.studyplanitem'),
        ),
    ]
