# Generated by Django 5.1.1 on 2026-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_mate_app', '0007_alter_studysession_study_plan_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='scheduled_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='session_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='shared_notes',
            field=models.TextField(blank=True),
        ),
    ]
