# Generated by Django 5.2.11 on 2026-04-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_mate_app', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
